# Generated by Django 4.2.13 on 2024-07-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_creatorgoal_supporters'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorgoal',
            name='funded_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
