# Generated by Django 4.2.13 on 2024-07-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_creatorgoal_funded_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporterinteraction',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
